##1


In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module): ## nn.module i inheritance from this class

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1) # input neuron  , output neuron
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)  # wx+= z
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1]) # means 5 , but use this becasue if change in dataset not effect , inplace of 5 may be 6,7

# call model for forward pass
# model.forward(features)
model(features) # standar way of calling forward function rather use above function model.forward(features)
# here they use magic method __call__ when object is created automatically constructor and forward method is called

tensor([[0.5789],
        [0.6290],
        [0.5422],
        [0.5581],
        [0.5891],
        [0.5073],
        [0.5969],
        [0.5904],
        [0.5652],
        [0.5721]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight # see weight similar bias

Parameter containing:
tensor([[ 0.2874,  0.2963, -0.3476, -0.2380, -0.0390]], requires_grad=True)

### 2

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module): ## nn.module i inheritance from this class

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3) # input neuron  , output neuron
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1) # hiddem layer 3*1+1 = 4   total 18+4 = 22 weight +bias
    self.Sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)  # wx+= z
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3609,  0.3073,  0.2204, -0.0006,  0.0749],
        [ 0.2985,  0.3812, -0.2263,  0.3835,  0.2449],
        [ 0.4393,  0.4203,  0.1985,  0.2825, -0.1818]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0780,  0.0211, -0.1835]], requires_grad=True)

### 3

In [ ]:
# other way and best way using sequentaial for large model
# include hidden layer # esay to forward pass function
# create model class
import torch
import torch.nn as nn

class Model(nn.Module): ## nn.module i inheritance from this class

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential( ## use sequentil conatiner to write again and again in forward method
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:

# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1]) # means 5 , but use this becasue if change in dataset not effect , inplace of 5 may be 6,7

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3500],
        [0.3364],
        [0.3429],
        [0.3284],
        [0.3392],
        [0.3647],
        [0.3458],
        [0.3252],
        [0.3743],
        [0.3507]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
# Accessing weights of the first linear layer within the network
model.network[0].weight

Parameter containing:
tensor([[-0.1016,  0.0030,  0.0768,  0.0096,  0.1214],
        [-0.2967, -0.3478, -0.3224,  0.3144,  0.2824],
        [ 0.1586, -0.0172,  0.2599,  0.3253,  0.1289]], requires_grad=True)

In [ ]:
model.network[1].weight

AttributeError: 'ReLU' object has no attribute 'weight'

In [ ]:
model.network[2].weight

Parameter containing:
tensor([[ 0.2585, -0.3723, -0.5014]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00